# Generated by Django 6.0.1 on 2026-01-17 20:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv4_address])),
                ('port', models.IntegerField(default=22)),
                ('username', models.CharField(max_length=100)),
                ('ssh_key', models.TextField(blank=True, help_text='SSH private key for authentication', null=True)),
                ('password', models.CharField(blank=True, help_text='Password (encrypted)', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=512)),
                ('project_type', models.CharField(choices=[('django', 'Django'), ('flask', 'Flask'), ('node', 'Node.js'), ('react', 'React'), ('angular', 'Angular'), ('other', 'Other')], max_length=50)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('repository_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_deployed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='servers.server')),
            ],
            options={
                'ordering': ['server', 'name'],
                'unique_together': {('server', 'name')},
            },
        ),
        migrations.CreateModel(
            name='NginxSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('config_path', models.CharField(max_length=512)),
                ('is_enabled', models.BooleanField(default=False)),
                ('has_ssl', models.BooleanField(default=False)),
                ('ssl_cert_path', models.CharField(blank=True, max_length=512, null=True)),
                ('ssl_key_path', models.CharField(blank=True, max_length=512, null=True)),
                ('upstream_port', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nginx_sites', to='servers.server')),
            ],
            options={
                'ordering': ['server', 'site_name'],
                'unique_together': {('server', 'site_name')},
            },
        ),
        migrations.CreateModel(
            name='ServerHealthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('disk_usage', models.FloatField()),
                ('network_in', models.FloatField(default=0)),
                ('network_out', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='servers.server')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['server', '-timestamp'], name='servers_ser_server__b19c53_idx')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('nginx', 'Nginx'), ('gunicorn', 'Gunicorn'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('redis', 'Redis'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('pid', models.IntegerField(blank=True, help_text='Process ID', null=True)),
                ('cpu_usage', models.FloatField(blank=True, help_text='CPU usage percentage', null=True)),
                ('memory_usage', models.FloatField(blank=True, help_text='Memory usage in MB', null=True)),
                ('config_path', models.CharField(blank=True, max_length=512, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='servers.server')),
            ],
            options={
                'ordering': ['server', 'name'],
                'unique_together': {('server', 'name')},
            },
        ),
    ]
